```{r, child="../../_styles.Rmd"}
```

## Workshop modules

Please use the links below to access materials (code, video, feeds) from R workshops. For new users, it is best to start with the introduction to R programming and then move on to more advanced topics. 

### Available workshop modules for R

<a href="./01_introToR.html">Introduction to programming in R</a> An introductory stroll through key concepts and syntax in R.

<a href="./01_fishStats.html">Introduction fisheries statistics in R</a> An introduction to methods and tools available for common fisheries analyses in R, including length-frequency histograms, length-weight regressions, growth curves, and proportional size distribution (PSD). Methods are demonstrated using base R functionality in addition to functions available through the `FSA` package for R (<a href="https://github.com/droglenc/FSA">Ogle et al. 2020</a>).

### References

Ogle, D.H., P. Wheeler, and A. Dinno. 2020. FSA: Fisheries Stock Analysis. R package version 0.8.30, https://github.com/droglenc/FSA.

<br> 
 