---
title: "Publications"
---

```{r, child="_styles.Rmd"}
```


### 2025

---

Stich, D. S., D. A. Fox, A. L. Higgs, D. C. Kazyak, R. M. Pendleton, and S. A. Sethi. 2025. Reconstructing relative abundance indices for Atlantic Sturgeon using hierarchical ecological models. Transactions of the American Fisheries Society 154:134-142. Open Access: [https://doi.org/10.1093/tafafs/vnae005](https://doi.org/10.1093/tafafs/vnae005)

Stich, D. S., J. L. Nieland, and T. F. Sheehan. 2025. dia: An R package for the National Oceanic and Atmospheric Administration dam impact analysis. Journal of Open Source Software. [https://doi.org/10.21105/joss.07475](https://doi.org/10.21105/joss.07475)


### 2024

---

Stich, D. S., W. E. Eakin, and G. Kenney. 2024. Population responses of blueback herring to dam passage standards and additive mortality sources. Journal of Fish and Wildlife Management 15(1):31–48. [Open Access](https://meridian.allenpress.com/jfwm/article/doi/10.3996/JFWM-23-016/501289/Population-Responses-of-Blueback-Herring-to-Dam).    


### 2023

---

George, S. D., B. P. Baldigo, C. B. Rees, M. L. Bartron, J. J. Wiley Jr., D. S. Stich, S. M. Wells, and D. R. Winterhalter. 2023. Use of environmental DNA to assess American Eel distribution, abundance, and barriers in a river-canal system. Transactions of the American Fisheries Society. doi: [https://doi.org/10.1002/tafs.10404](https://doi.org/10.1002/tafs.10404). [Open access](https://afspubs.onlinelibrary.wiley.com/doi/full/10.1002/tafs.10404)

Poulet, C., G. Lassalle, A. Jordaan, K. Limburg, C. Nack, J. Nye, A. O’Malley, B. O’Malley-Barber, D. Stich, J. Waldman, J. Zydlewski, and P. Lambert. 2023. Effect of straying, reproductive strategies, and ocean distribution on the structure of American shad populations. Ecosphere 14:e4712.doi: [https://doi.org/10.1002/ecs2.4712](https://doi.org/10.1002/ecs2.4712) [Open access](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecs2.4712).

Zydlewski, J., S. Coghlan, C. Dillingham, G. Figueroa-Muñoz, C. Merriam, M. Payne Wynne, S. Smith, R. Smith, D. Stich, S. Vogel, K. Wilson, and G. Zydlewski. 2023. Seven dam challenges for migratory fish: insights from the Penobscot River. Frontiers in Ecology and Evolution. [Open access](https://www.frontiersin.org/articles/10.3389/fevo.2023.1253657/full)


### 2022

---

Erikson, R. A., D. S. Stich, and J. L. Hebert. 2022. fishStan: Hierarchical Bayesian models for fisheries. Journal of Open Source Software. doi: 10.21105/joss.03444. [Open access](https://www.theoj.org/joss-papers/joss.03444/10.21105.joss.03444.pdf)

Molina-Moctezuma, A., D. S. Stich, and J. D. Zydlewski. 2022. Effects of dam-induced delays on system-wide survival of Atlantic salmon smolts during high-flow, high-survival years in the Penobscot River, Maine, USA. Canadian Journal of Fisheries and Aquatic Sciences 79:2237–2250. doi: [https://doi.org/10.1139/cjfas-2022-0055](https://doi.org/10.1139/cjfas-2022-0055)


### 2021

---

Caves, S., J. R. Baumann, and D. S. Stich. 2021. Density-dependent changes in Grass Carp growth and mortality in long-term aquatic plant management. North American Journal of Fisheries Management 41:355-365. <a href="https://github.com/danStich/grasscarp"> [code]</a>

George, S. D., D. S. Stich, and B. P. Baldigo. 2021. Considerations of variability and power for long-term monitoring of stream fish assemblages. Canadian Journal of Fisheries and Aquatic Sciences 78:301-311. [Open access](https://cdnsciencepub.com/doi/pdf/10.1139/cjfas-2020-0013).

Gilligan-Lunda, E. K., D. S. Stich, K. E. Mills, M. M. Bailey, and J. D. Zydlewski. 2021. Climate change may cause shifts in growth and instantaneous natural mortality of American Shad throughout their native range. Transactions of the American Fisheries Society 150:407-421.

Oliver, D. O., N. Rude, G. W. Whitledge, and D. S. Stich. 2021. Evaluation of recently implemented harvest regulations in a data-limited catfish fishery with Bayesian estimation. North American Journal of Fisheries Management 41:S364-S378.

Sotola, V. A., K. T. Sullivan, B. M. Littrell, N. H. Martin, D. S. Stich, and T. H. Bonner. 2021. Short-term responses of freshwater mussels to floods in a southwestern U.S.A. river estimated using mark-recapture sampling. Freshwater Biology 66:349-361.<a href = "https://github.com/vasotola/MusselMarkRecap"> [code]</a>

Vlk, A., E. Bastiaans, D. Stich, and D. Vogler. 2021. Effect of
anthropogenic habitat disturbance on the nesting ecology of the wood 
turtle (*Glyptemys insculpta*). Amphibian and Reptile Conservation 15(2):50-58.

Zydlewski, J., D. S. Stich, S. Roy, M. Bailey, T. Sheehan, and K. Sprankle. 2021. What Have We Lost? Modeling Dam Impacts on American Shad Populations Through Their Native Range. Frontiers in Marine Science.
<a href = "https://www.frontiersin.org/articles/10.3389/fmars.2021.734213/full"> [Open access] <a href = "https://github.com/danStich/anadrofish"> [anadrofish R package]</a>.

### 2019

---

Watson, J. M., S. M. Coghlan, J. D. Zydlewski, D. B. Hayes, and D. S. Stich. 2019. Role of recovering river herring Alosa spp. populations on Smallmouth Bass diet and growth. Pages 75-92 in M. J. Seipker and J. W. Quinn Editors, Managing Centrarchid Fisheries, American Fisheries Society Symposium Number 87. American Fisheries Society, Bethesda, MD. 
<!-- <a href="./pubs/Watson_etal_2019_AFS87.pdf">[PDF]</a> -->

George, S. D., B. P. Baldigo, and D. S. Stich. 2019. Temporal variability in stream fish assemblage metrics and implications for long-term monitoring. Ecological Indicators 101:661-669. <a href="https://www.sciencedirect.com/science/article/pii/S1470160X19300731">[Link]</a> <a href="https://github.com/danStich/longtermCommunityMetrics"> [code]</a>

Franzem, T. P., M. Kugler, R. LaRochelle, <b>D. Stich</b>, A. Gascho Landis, and P. Lord. 2019. Reproductive phenology of *Elliptio complanata* in the Upper Susquehanna River tributaries of New York. Northeastern Naturalist 29:119-128. <a href="https://github.com/danStich/elliptioPhenology"> [code]</a>

Stich, D. S., T. F. Sheehan, and J. D. Zydlewski. 2019. A dam passage performance standard model for American Shad. Canadian Journal of Fisheries and Aquatic Sciences 76:762-779. <a href="https://github.com/danStich/shadia"> [`shadia` R package]</a>


### 2017

---
 
Hawkes, J. P., T. F. Sheehan, and D. S. Stich. 2017. Assessment of early migration dynamics of river-specific hatchery Atlantic salmon smolts. Transactions of the American Fisheries Society 146:1279-1290. 
<!-- <a href="./pubs/Hawkes_etal_2017_TAFS_Dennys.pdf">[PDF]</a> -->


Zydlewski, J., D. Stich, and D. Sigourney. 2017. Hard choices in assessing survival past dams; a comparison of single and paired release strategies. Canadian Journal of Fisheries and Aquatic Sciences 74:178-190. 
<!-- <a href="./pubs/Zydlewski_etal_2016_CJFAS_HardChoices.pdf">[PDF]</a> -->


### 2016

---
 
Stich, D. S., G. Zydlewski, and J. D. Zydlewski. 2016. Physiological preparedness and performance of *Salmo salar* smolts in relation to behavioural salinity preferences and thresholds. Journal of Fish Biology 88:595-617. 
<!-- <a href="./pubs/Stich_etal_2016_JFB_Salinity.pdf">[PDF]</a> -->


### 2015

---
 
Stich, D. S., M. T. Kinnison, J. F. Kocik, and J. D. Zydlewski. 2015. Initiation of migration and movement rates of Atlantic Salmon smolts in fresh water. Canadian Journal of Fisheries and Aquatic Sciences 72:1339-1351.
<!-- <a href="./pubs/Stich_etal_2015_CJFAS_behavior.pdf" >[PDF]</a> -->

Stich, D. S., M. M. Bailey, C. M. Holbrook, M. T. Kinnison, J. D. Zydlewski. 2015. Catchment-wide survival of wild- and hatchery-reared Atlantic Salmon smolts in a changing system. Canadian Journal of Fisheries and Aquatic Sciences 72:1352-1365.
<!-- <a href="./pubs/Stich_etal_2015_CJFAS_survival.pdf">[PDF]</a>. -->

Stich, D. S., J. F. Kocik, G. B. Zydlewski, and J. D. Zydlewski. 2015. Linking behavior, physiology, and survival of Atlantic Salmon smolts during estuary migration. Marine and Coastal Fisheries: Dynamics, Management, and Ecosystem Science 7:68-86.
<!-- <a href="./pubs/Stich_etal_2015_MCF_Estuary.pdf" >[PDF]</a> -->

Stich, D. S., Y. Jiao, and B. R. Murphy. 2015. Life, death, and resurrection: Accounting for state uncertainty in survival estimation from radio-tagged Grass Carp. North American Journal of Fisheries Management 35:321-330. <a href="https://github.com/danStich/lazarus">[code]</a>
<!-- <a href="./pubs/Stich_etal_2015_NAJFM_Lazarus.pdf">[PDF]</a>  -->


### 2014

---
 
Stich, D. S., M. Bailey, J. D. Zydlewski. 2014. Survival of Atlantic Salmon *Salmo salar* smolts through a hydropower complex. Journal of Fish Biology 85:1074-1096. 
<!-- <a href="./pubs/Stich_etal_2014_JFB_MarshIsland.pdf">[PDF]</a> -->

Zydlewski, G. B., D. S. Stich, and S. D. McCormick. 2014. Photoperiod control of the initiation of downstream migration in Atlantic Salmon smolts. Journal of Fish Biology 85:1023-1041. 
<!-- <a href="./pubs/Zydlewski_etal_2014_JFB.pdf">[PDF]</a> -->

 
### 2013

---
 
Stich, D. S., V. Dicenzo, E. Frimpong, Y. Jiao, and B. R. Murphy. 2013. Growth and population size of Grass Carp incrementally stocked for control of hydrilla. North American Journal of Fisheries Management 33:14-25. 
<!-- <a href="./pubs/Stich_etal_2013_NAJFM_grassCarp.pdf">[PDF]</a> -->
