```{r, child="_styles.Rmd"}
```

---
title: "Instructors"
---

<br>

<br>
 
##### **Lisa Borre**
Lisa is a Senior Research Specialist at the Cary Institute of Ecosystem Studies, and is the NALMS Region 3 Director. She is a co-liason for the NALMS Secchi Dip-In program, an active member in the Global Lake Ecological Observatory Network (GLEON), and Project Coordinator for the Lake Observer app.

<br>
 
##### **Sarah Burnett**
Sarah is a PhD student at the University of Idaho, and the NALMS Student Director. Her research is focused on internal loading of phosphorus leading to algal blooms.

<br>
 
##### **Dana Stephens**
Dana has experiencing large databases, including North American Secchi data, and used various statistical analyses to examine temporal and spatial components of these data.

<br>
 
##### **Dan Stich**
Dan is an Assistant Professor in the Biology Department at SUNY Oneonta, where he teaches undergraduate and graduate courses in biometry using R. He also works extensively with R in his research, which is focused on quantitative aspects of fisheries management. He recently developed his first R package, <a  href="https://github.com/danStich/shadia"> shadia </a>, in collaboration with a graduate student and a scientific programmer at the University of Buffalo.

<br>
 
<br>
 